### ISSUE TITLE
Site generate incomplete / fails without error

### ISSUE THREAD

**Issue by julrichkieffer** [avisi-cloud/structurizr-site-generatr#41] opened 2022-09-01 13:41 UTC
## Problem

Site generate incomplete / fails without error when the following DSL is used: 

```structurizr
workspace "multi-relationships-summary" {

	model {
		cpq = softwareSystem "CPQ" "" "Web Browser"

		admin = person "Admin" {
			-> cpq "administers"
		}
		user = person "CPQ User" "" "Bank Staff" {
			-> cpq "uses"
		}
	}

	views {
		systemLandscape {
			autoLayout
			// show all static relationships and entities (see model)
			include *
		}

		dynamic * "CPQAdmin" {
			autoLayout
			title "CPQ Administration"

			// include static relationship; no change to relationship as only the parties are identified
			user -> cpq

			// replace static relationship; parties are identified but new relationships (both directions) are shown in this view only
			admin -> cpq "maintains products"
			admin -> cpq "maintains pricing"
			admin -> cpq "maintains promotions"
			admin -> cpq "maintains cross-selling"
			cpq -> admin "report abandonned carts"
			cpq -> admin "report sales overrides"
		}
	}
}
```

Expected

While the CPQ system page is created, neither the landscape nor dynamic `CPQ Admin` page is found in the generated website.

**Comment by dirkgroot** [comment] 2022-09-07 10:49
There is no error message, because no errors occur. What you're seeing is caused by 2 things:

1. No page is automatically created for the system landscape diagram. The system landscape diagram can be included in the site by adding a documentation Markdown file with the system landscape diagram embedded, as can be seen in the [example site](https://avisi-cloud.github.io/structurizr-site-generatr/main/system-landscape/).
2. The site generator does generate images, but doesn't generate pages for dynamic diagrams.

**Comment by dirkgroot** [comment] 2022-11-10 16:34
Closing this issue, because this is intended behaviour.

**Closed by dirkgroot** 2022-11-10 16:34 UTC
