### ISSUE TITLE
Intended that "Legend" renders with CSS hints, like `(last back color, $lineStyle, thickness 1)`

### ISSUE THREAD

**Issue by spex66** [avisi-cloud/structurizr-site-generatr#469] opened 2024-03-28 11:02 UTC
Still enjoying the power of your structurizr tooling 🚀
Run into this rendering-issue and reproduced it with the docs/example.

## Reproduction steps

- checked out this repo (pulled latest)
- pulled latest docker image v1.2.0 (observed it first with version v1.1.8)
- run
```
cd docs
docker run -it --rm --user root -p 8080:8080 -v $(pwd)/example:/var/example ghcr.io/avisi-cloud/structurizr-site-generatr serve -w /var/example/workspace.dsl -a /var/example/assets -s /var/build
```

## Issue
- the legend looks in Firefox and Chrome (on Windows11) for <http://localhost:8080/master/internet-banking-system/context/> like this
![image](https://github.com/avisi-cloud/structurizr-site-generatr/assets/1098323/5aaea275-f7f2-4691-85ef-63c6846ba683)
- are those information added in brackets intended? Not an expert, but looks like CSS shines through?
- DOM snippet for top two `<rect>` added FYI
![image](https://github.com/avisi-cloud/structurizr-site-generatr/assets/1098323/f3cf34aa-c0a7-456d-a15c-18b5cb736b59)

(not sure if discussion related to in #163 which was the only other issue related to "legend")

**Comment by jp7677** [comment] 2024-03-29 11:07
Thanks for the report. This looks like a duplicate of https://github.com/structurizr/java/issues/263 and should thus be fixed with the next dependency update.

**Closed by jp7677** 2024-03-29 11:07 UTC
