### ISSUE TITLE
Error: `No viewBox attribute found in SVG!`

### ISSUE THREAD

**Issue by nc-at-sp** [avisi-cloud/structurizr-site-generatr#279] opened 2023-07-27 12:33 UTC
I get this issue when attempting to serve my site locally.  My model is relatively large and complex.  This error does not _always_ happen; if I exit and re-execute multiple times it will eventually work.  It feels like a race condition or some other kind of threading issue to me.

OS: `WSL (Ubuntu)`
Java:  `20.0.1 2023-04-18`
structurizr-site-generatr version `v1.1.4`

`structurizr-site-generatr serve -w my-file.dsl`

```
java.lang.IllegalStateException: java.lang.IllegalStateException: No viewBox attribute found in SVG!
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.generateHtmlFiles(SiteGenerator.kt:158)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.generateSite(SiteGenerator.kt:71)
        at nl.avisi.structurizr.site.generatr.ServeCommand.updateSite(ServeCommand.kt:82)
        at nl.avisi.structurizr.site.generatr.ServeCommand.execute(ServeCommand.kt:50)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
        at nl.avisi.structurizr.site.generatr.AppKt.main(App.kt:13)
Caused by: java.lang.IllegalStateException: No viewBox attribute found in SVG!
        at nl.avisi.structurizr.site.generatr.site.model.DiagramViewModel$Companion.extractDiagramWidthInPixels(DiagramViewModel.kt:40)
        at nl.avisi.structurizr.site.generatr.site.model.DiagramViewModel$Companion.forView(DiagramViewModel.kt:28)
        at nl.avisi.structurizr.site.generatr.site.model.DiagramViewModel$Companion.forView(DiagramViewModel.kt:16)
        at nl.avisi.structurizr.site.generatr.site.model.SoftwareSystemComponentPageViewModel.<init>(SoftwareSystemComponentPageViewModel.kt:12)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$1$8$4.invoke(SiteGenerator.kt:133)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$1$8$4.invoke(SiteGenerator.kt:133)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$2.invoke(SiteGenerator.kt:158)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$2.invoke(SiteGenerator.kt:158)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.generateHtmlFiles$lambda$17(SiteGenerator.kt:158)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by nc-at-sp** [comment] 2023-07-27 12:34
Also, I cannot share my model file as it contains proprietary data.

**Comment by dirkgroot** [comment] 2023-08-11 08:44
Hi @nc-at-sp, thanks for reporting this issue.

I'm not sure what causes this. Could you try reproducing this issue and then see if there's SVG's in the `build` directory, that don't contain a `viewBox` attribute, or that have a `viewBox` attribute that does not match this regular expression: `\d+ \d+ \d+` (that's what this tool is looking for).

**Comment by nc-at-sp** [comment] 2023-08-11 11:45
Good morning.

I went and checked every SVG file in the build directory.  Each contains a viewBox attribute.  Each looks like a variant of:

viewBox="0 0 488 538"​

Each has 4 numbers (I'm assuming the regex below is just missing a 4th \d+​ since it's not a viewTriangle)

I also went through each page in the  build/master​ and inspected each <svg>​ element, and all are as expected.

If you could add a detail to the log saying which file is the problem, I can dive in and focus on that file.

What's interesting is that if I hit "F5" to refresh, the entire page renders correctly just for a second​ and then the error appears.

Also, this is not reliably repeatable. Exiting and running serve​ again will eventually give me a good session. But even if I don't change anything, and just exit and run serve​ again, the issue will eventually appear again.  Hence my hypothesis about some kind of race condition.

Thanks for your attention!

Nate Carpenter Chief Technology Officer
202-333-0159 (Office) | 202-333-0109 (Fax) | 202-339-6290 (Direct)
SECURIPORT, LLC
www.securiport.com<http://www.securiport.com/>



________________________________

**Comment by nc-at-sp** [comment] 2023-08-11 12:41
At least in my instance they're always `0` `0`

**Comment by dirkgroot** [comment] 2023-09-08 08:08
@nc-at-sp Okay, thanks. This looks like some kind of race condition indeed. I think I know where this occurs. Just for confirmation: Do you have diagrams that you have embedded in multiple documentation files using the `![](embed:diagram_key)` syntax?

**Comment by dirkgroot** [comment] 2023-09-08 09:25
@nc-at-sp I've set up a PR with a possible fix for this issue (#308). Could you test if that change solves this issue?

You can download the binaries produced by this PR using [this link](https://github.com/avisi-cloud/structurizr-site-generatr/suites/15953774102/artifacts/910776875).

**Comment by nc-at-sp** [comment] 2023-09-08 11:58
That seems to have done the trick; attempted 10 or so reloads and didn't see the issue once. Seems to be generally faster as well.  Thanks!

**Comment by dirkgroot** [comment] 2023-09-11 11:40
Thanks for testing, @nc-at-sp! I've merged the PR, and will create a release somewhere this week. I'm closing this issue.

**Closed by dirkgroot** 2023-09-11 11:40 UTC

**Comment by oneacik** [comment] 2023-09-25 11:43
Hello @dirkgroot,
when the docker image will be available with this fix?
Cheers.
