### ISSUE TITLE
Mounting local folder to `/var/model` appears broken 

### ISSUE THREAD

**Issue by julrichkieffer** [avisi-cloud/structurizr-site-generatr#31] opened 2022-08-23 12:41 UTC
On review of the `Dockerfile`, I learn that:
 - the working folder of the image is set to `/var/model`
 - a volume mount is defined at `/var/model` 
 - input `.dsl` files are expected by `serve` and `generate-site` operations to exist at `/var/model`

Therefore, I have included the `-v [local folder]:/var/model` option when running this image, yet the below always gives rise to a "File does not exist" error:

```sh
> ls
    Directory: C:\Projects\learning\c4


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        20/08/2022     14:55                .devcontainer
d-----        22/08/2022     18:37                puml
-a----        20/08/2022     16:13             41 .gitignore
-a----        20/08/2022     19:25           2516 amazon-web-service.dsl
-a----        22/08/2022     18:35            582 azure.dsl
-a----        20/08/2022     19:24          11841 big-bank.dsl
-a----        20/08/2022     16:10            234 build.sh
-a----        20/08/2022     19:23           6549 c4-dsl-extension.dsl
-a----        22/08/2022     18:43           2977 cookbook.dsl
-a----        20/08/2022     19:21           3248 financial-risk.dsl
-a----        22/08/2022     14:01            590 workspace-extension.dsl
-a----        20/08/2022     15:31            730 workspace.dsl

> docker run -it --rm -v /projects/learning/c4:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9 serve -w cookbook.dsl 
Exception in thread "main" com.structurizr.dsl.StructurizrDslParserException: The file at /var/model/cookbook.dsl does not exist
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:119)
        at nl.avisi.structurizr.site.generatr.StructurizrUtilitiesKt.parseStructurizrDslWorkspace(StructurizrUtilities.kt:11)
        at nl.avisi.structurizr.site.generatr.ServeCommand.updateSite(ServeCommand.kt:50)
        at nl.avisi.structurizr.site.generatr.ServeCommand.execute(ServeCommand.kt:33)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
        at nl.avisi.structurizr.site.generatr.AppKt.main(App.kt:13)
```

By running the image with `-itd` instead, and `docker inspect [container id] > image-inspect.txt` thereafter, the 
[attached image-inspect.txt file](https://github.com/avisi-cloud/structurizr-site-generatr/files/9402552/image-inspect.txt) shows Docker's internals, specifically that the mounting itself worked.

1. Could this be a permission issue, since the image is running on `USER 65532`? 
2. Could a new operation eg. `list` be created to list all files the container "sees" at `/var/model`?
3. Could this be absent documentation that explains how to use the image with local `.dsl` files?

**Comment by julrichkieffer** [comment] 2022-08-23 12:43
For clarity, I'm running:
- Windows 10 Home
- WSL2
- Windows Terminal 2

**Comment by dirkgroot** [comment] 2022-08-24 07:28
Hi @julrichkieffer, I think your problem is that in WSL, the `C:` drive is mounted under `/mnt/c`. See https://docs.microsoft.com/en-us/windows/wsl/file-permissions#accessing-files-in-the-windows-drive-file-system-drvfs-from-linux.

So your command should be:

```shell
docker run -it --rm -v /mnt/c/projects/learning/c4:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9 serve -w cookbook.dsl 
```

**Comment by dirkgroot** [comment] 2022-08-24 07:36
I'm not sure if Homebrew works on WSL, but if it does, you could also install Structurizr Site Generatr using Homebrew. I would recommend to do that, because primary goal for the Docker image is to be used from a build pipeline.

**Comment by dirkgroot** [comment] 2022-08-24 09:20
Oh, and I now realize that the `VOLUME` and `WORKDIR` are probably slightly misleading. In reality there's no requirement that the model should be located in `/var/model`. You can mount it in any directory you like, as long as you specify the full path to the DSL file with the `-w` parameter.

Example:

```shell
docker run -it --rm -v /mnt/c/projects/learning/c4:/var/mycoolmodel ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9 serve -w /var/mycoolmodel/cookbook.dsl
```

**Comment by julrichkieffer** [comment] 2022-08-25 16:34
Hi @dirkgroot 

My primary use case *is* to use this container in a build pipeline ::check:: But I first need to get it working on WSL2 as per my current dev environment ::cross::. The whole point of Docker containers is to be self-contained and poratble. So I dont want a dependency (ie Homebrew) that 1. isn't necessary, 2. already in the container, or 3. introduces a dependency into the CI pipeline. 

I didn't remember, but totally agree that `/mnt/c/...` is the appropriate notation. However, owing to the `ENTRYPOINT` being set, I can only rely on structurizr-site-generatr to learn if my volume and -w paramters have any effect. This is why I suggested a `list` command, though it may be future proof to instead have an `inspect` command return a json result that inludes an array of files in the workspace. Future needs can extend the json response without affecting the API.

Currently, no matter what combination of volume and workspace paths I supply, the same error (as above) is returned.

**Comment by julrichkieffer** [comment] 2022-08-25 17:46
Hi @dirkgroot 

Good news! 

By removing the structurizr-site-generatr and `ENTRYPOINT` commands, I found the mounted volume over WSL and file access (with `USER 65532`) is succesful.  Here's my triage process:

1.  Create a new `Dockerfile`, commenting out the structurizr-site-generatr installation and `ENTRYPOINT` commands. Although not required, but as suggested earlier, I appended a default `CMD ["ls", "-lah"]` command, which means you'll see a formatted list of the files in the mounted `/var/model` by default. See [attached](https://github.com/avisi-cloud/structurizr-site-generatr/files/9427072/Dockerfile.txt).

1.  I built a local image with `docker build -t generatr/local:latest .` Notice the image `generatr/local` is used from hereon

1.  I ran the local image, and the mounted volume's content is returned as expected:

```sh
> docker run -it --rm -v c:/projects/learning/c4:/var/model generatr/local

drwxrwxrwx 1 root root 4.0K Aug 25 17:24 .
drwxr-xr-x 1 root root 4.0K Aug 25 16:56 ..
-rw-r--r-- 1 1000 1000 2.5K Aug 20 18:25 amazon-web-service.dsl
-rw-r--r-- 1 1000 1000  582 Aug 22 17:35 azure.dsl
-rw-r--r-- 1 1000 1000  12K Aug 20 18:24 big-bank.dsl
-rwxr-xr-x 1 1000 1000  234 Aug 20 15:10 build.sh
-rw-r--r-- 1 1000 1000 6.4K Aug 20 18:23 c4-dsl-extension.dsl
-rw-r--r-- 1 1000 1000 3.0K Aug 22 17:43 cookbook.dsl
drwxrwxrwx 1 root root 4.0K Aug 20 13:55 .devcontainer
-rwxrwxrwx 1 root root  542 Aug 25 17:17 Dockerfile
-rw-r--r-- 1 1000 1000 3.2K Aug 20 18:21 financial-risk.dsl
-rwxrwxrwx 1 root root   82 Aug 25 17:12 generatr-build.bat
-rw-r--r-- 1 1000 1000   41 Aug 20 15:13 .gitignore
-rwxrwxrwx 1 root root  19K Aug 23 12:33 image-inspect.txt
drwxr-xr-x 1 1000 1000 4.0K Aug 22 17:37 puml
-rw-r--r-- 1 1000 1000  730 Aug 20 14:31 workspace.dsl
-rw-r--r-- 1 1000 1000  590 Aug 22 13:01 workspace-extension.dsl
```

4. To check file read access across WSL2 to the local `c:/projects/learning/c4` folder (with `USER 65532`):

```sh
> docker run -it --rm -v c:/projects/learning/c4:/var/model generatr/local cat azure.dsl

workspace {
    model {
        softwareSystem "Authentication Service" {
            tags "Microsoft Azure - Azure Active Directory"
        }
    }

    views {
                        systemLandscape {
                                        include *
                                        autoLayout lr
                        }

                        systemLandscape "Azure" {
                                !script groovy {
                                                view = workspace.views.getViewWithKey("Azure");
                                                workspace.model.softwareSystems.findAll {it.hasTag("Microsoft Azure - Azure Active Directory") }.each{ view.add(it); };
                                }
                                autolayout
                        }
        theme https://static.structurizr.com/themes/microsoft-azure-2021.01.26/theme.json
    }
}
```

5.  Lastly, to check writing files from the container to the local `c:/projects/learning/c4` folder (with `USER 65532`):

```sh
> docker run -it --rm -v c:/projects/learning/c4:/var/model generatr/local touch index.html
> ls

    Directory: C:\Projects\learning\c4


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        20/08/2022     14:55                .devcontainer
d-----        22/08/2022     18:37                puml
-a----        20/08/2022     16:13             41 .gitignore
-a----        20/08/2022     19:25           2516 amazon-web-service.dsl
-a----        22/08/2022     18:35            582 azure.dsl
-a----        20/08/2022     19:24          11841 big-bank.dsl
-a----        20/08/2022     16:10            234 build.sh
-a----        20/08/2022     19:23           6549 c4-dsl-extension.dsl
-a----        22/08/2022     18:43           2977 cookbook.dsl
-a----        25/08/2022     18:17            542 Dockerfile
-a----        20/08/2022     19:21           3248 financial-risk.dsl
-a----        25/08/2022     18:12             82 generatr-build.bat
-a----        23/08/2022     13:33          19188 image-inspect.txt
-a----        25/08/2022     18:31              0 index.html
-a----        22/08/2022     14:01            590 workspace-extension.dsl
-a----        20/08/2022     15:31            730 workspace.dsl
```

Which means **I've exluded WSL2, volume mounts, and file read or writing operations from within the container as the source of the runtime exception**. So I think the issue lies within structurizr-site-generatr (or the Java runtime) itself.

**Comment by dirkgroot** [comment] 2022-08-26 06:17
Hi @julrichkieffer, thanks for your research! I don't use Windows, so I can't easily reproduce your issue myself, so your input is really helpful!

In your previous attempt you have been using `/projects/learning/c4` and `/mnt/c/projects/learning/c4` to specify the host path with the `-v` argument. You now have seen a working volume mount by using `c:/projects/learning/c4` as the host path. Upon doing some more research this makes sense, because Docker's [documentation on volume mounts](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only) states:

> On Windows, the paths must be specified using Windows-style semantics.

Just double checking: Did you also attempt to use `c:/projects/learning/c4` with the `structurizr-site-generatr` Docker image? If you did, what's the exact error message you get?

Like this:

```shell
> docker run -it --rm -v c:/projects/learning/c4:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9 serve -w workspace.dsl
```

Or like this:

```shell
> docker run -it --rm -v c:/projects/learning/c4:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9 serve -w /var/model/workspace.dsl
```

**Comment by julrichkieffer** [comment] 2022-08-26 11:05
Hi @dirkgroot 

Yes, to do the WSL2 triage yesterday I removed as much "magic" as I could. So I used full absolute paths instead.  

And again, **good news!**  By applying the full path to the volume mount, we get farther with `ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9` **but with a new runtime (java) error**:

```sh
> docker run -it --rm -v c:/projects/learning/c4:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9 serve -w cookbook.dsl

Generating diagrams...
PetClinic-Dynamic-001...
Development-Deployment...
landscape...
PetClinic-SystemContext...
PetClinic-Container...
Production-Deployment...
PetClinic-WebApplication-Component...
Generating site...
Successfully generated diagrams and site
Starting server...
[main] INFO org.eclipse.jetty.server.Server - jetty-11.0.11; built: 2022-06-21T21:42:55.454Z; git: 58487315cb75e0f5c81cc6fa50096cbeb3b9554e; jvm 18.0.2+9
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@62ea3440{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@299321e2{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[main] INFO org.eclipse.jetty.server.Server - Started Server@45905bff{STARTING}[11.0.11,sto=0] @20306ms
Server started
Open http://localhost:8080 in your browser to view the site
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because the return value of "java.io.File.getParentFile()" is null
        at nl.avisi.structurizr.site.generatr.ServeCommand.startWatchService(ServeCommand.kt:94)
        at nl.avisi.structurizr.site.generatr.ServeCommand.execute(ServeCommand.kt:35)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
        at nl.avisi.structurizr.site.generatr.AppKt.main(App.kt:13)

.... the process locks (i.e. doesn't exit) here until I press ctrl+C to return to the command prompt (`>`).
```

Off course, the runtime error above is related to the `serve` operation. If instead I use the `generate-site` operation, we get success 🥇 :

```sh
> docker run -it --rm -v c:/projects/learning/c4:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9 generate-site -w cookbook.dsl

PetClinic-Dynamic-001...
PetClinic-SystemContext...
Production-Deployment...
landscape...
Development-Deployment...
PetClinic-WebApplication-Component...
PetClinic-Container...
```

In trying my other .dsl files using `serve`, some give the same mixed response -- generated output but locks after runtime error -- and others fail with other exceptions owing to `!script` or other issues arrising from the `.dsl` content itself. That is, once we get past the above runtime exception and locking, we still have some issues to remedy or Structurizr features to support.  But those are good problems to have :)

So to support your debugging, I've attached my [c4 folder](https://github.com/avisi-cloud/structurizr-site-generatr/files/9432559/c4.zip). I just copy-pasted .dsl files from several places -- to get a range of Structurizr features -- so there may be syntax errors in the .dsl.  It's only `cookbook.dsl` that I wrote from scratch myself by following the [Structurizr Cookbook learning path](https://github.com/structurizr/dsl/tree/master/docs/cookbook), which is why I used it in earlier triage.

**Comment by dirkgroot** [comment] 2022-08-26 11:22
Hi @julrichkieffer, that's good news! The error message you got has already been fixed on `main` (see #33). You can work around it by specifying the full path to the workspace file, eg. `/var/model/cookbook.dsl`.

I'll look into the fonts directory that's being created, I've also seen that happen. It's definitely not part of the generated site, so you can safely ignore it.

**Comment by dirkgroot** [comment] 2022-08-26 11:25
Oh, and I'll look at the workspaces in the c4 folder you attached as well.

**Comment by julrichkieffer** [comment] 2022-08-26 11:30
Ok. 

I think the mounting issue is safely closed with some updated documentation which I'd be happy to write. But I suggest we create child issues from above's triage, so we don't lose each bug in here (however minor they may be).  For example, on looking at the `build` folder, although the images (puml and svg) are generated, only the Home and Systems html pages are generated -- not others.  I don't know if this is because the generator is failing silently, or because it expects all `.dsl` files to have a `!docs docs` entry.

But let me try with your suggestion, and report back....

**Comment by julrichkieffer** [comment] 2022-08-26 11:40
Update on `serve` operation:

First, without exposing a port, you won't get networking. So I have updated the command, and found `serve` now works:

```sh
> docker run -it --rm -p 8080:8080 -v c:/projects/learning/c4:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9 serve -w /var/model/cookbook.dsl

Generating diagrams...
landscape UP-TO-DATE
PetClinic-Dynamic-001 UP-TO-DATE
PetClinic-SystemContext UP-TO-DATE
Development-Deployment UP-TO-DATE
PetClinic-Container UP-TO-DATE
PetClinic-WebApplication-Component UP-TO-DATE
Production-Deployment UP-TO-DATE
Generating site...
Successfully generated diagrams and site
Starting server...
[main] INFO org.eclipse.jetty.server.Server - jetty-11.0.11; built: 2022-06-21T21:42:55.454Z; git: 58487315cb75e0f5c81cc6fa50096cbeb3b9554e; jvm 18.0.2+9
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@b1712f3{/,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@332729ad{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[main] INFO org.eclipse.jetty.server.Server - Started Server@34c01041{STARTING}[11.0.11,sto=0] @1552ms
Server started
Open http://localhost:8080 in your browser to view the site
```

But as explained just above, not all pages / navigation paths are generated. So HTTP 404 errors are returned when trying to drill down to actual workspace content:

![image](https://user-images.githubusercontent.com/895332/186895592-87f8df94-32a7-497d-9193-c2223b6651e7.png)

**Comment by dirkgroot** [comment] 2022-08-26 11:41
I've had a quick look at the workspaces from your attachment. As a result, I've created 2 issues: #34 and #35. When I have more time, I'll look a bit more closely.

Thanks for your feedback so far, it's been really helpful! And feel free to create a PR with improved documentation on the volume mounting on WSL2.

**Comment by julrichkieffer** [comment] 2022-08-26 12:09
I'm glad to partner with you to help / make things better. So thank you too.  👏 

The bugs found during the triage above:
- [ ] ENTRYPOINT in the Dockerfile prevents runtime triage. Instead, rather specify the same entrypoint as a default by using the `CMD` command instead
- [ ] `serve` and `generate-site` operations lock (don't exit) when a runtime exception is unhandled
- [ ] downloaded fonts needed by `generate-site` are found outside the `build` output folder
- [ ] there's no way to set the output folder for the `generate-site` command
- [ ] include port mapping (`-p 8080:8080`) in documentation of `serve` operation
- [ ] runtime error unless the workspace is specified with a full path (e.g. `serve -w /var/model/cookbook.dsl`) inside the container. That is, container internals knowledge required.  Documentation needs updating to include this workaround. 
- [ ] mounting a local folder from Windows over WSL2 requires a full path. This is a known issue. However documentation here needs updating to reflect this
- [ ] not all workspace views can be found in generated output despite .puml and .svg folders holding images as expected. Does the generator require a `!docs docs` command in the workspace .dsl?
- [ ] Structurizr `!script` command not yet supported

**Comment by dirkgroot** [comment] 2022-08-29 08:25
A few quick remarks:

> * [ ]  ENTRYPOINT in the Dockerfile prevents runtime triage. Instead, rather specify the same entrypoint as a default by using the `CMD` command instead

The entrypoint can be overridden using the `--entrypoint` argument of `docker run`. I think this is sufficient for runtime triage. For example:
```shell
> docker run -it --rm -v $(pwd)/model:/var/model --entrypoint bash ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.9
```

> * [ ]  there's no way to set the output folder for the `generate-site` command

There is. You can use the `--output-dir` option. See `structurizr-site-generatr generate-site --help`.

> * [ ]  runtime error unless the workspace is specified with a full path (e.g. `serve -w /var/model/cookbook.dsl`) inside the container. That is, container internals knowledge required.  Documentation needs updating to include this workaround.

This has already been fixed on `main`. See #33.

> * [ ]  not all workspace views can be found in generated output despite .puml and .svg folders holding images as expected. Does the generator require a `!docs docs` command in the workspace .dsl?

I think this is caused by the issue described in #35.

> * [ ]  Structurizr `!script` command not yet supported

See #34.

**Comment by dirkgroot** [comment] 2022-08-29 09:11
> * [ ]  downloaded fonts needed by `generate-site` are found outside the `build` output folder

See #36.

**Closed** 2022-10-21 06:36 UTC
